version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: ChatGPTDb
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-mongodb}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-mongodb}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-mongodb}
      MONGO_USER_NAME: ${MONGO_USER_NAME:-mongouser}
      MONGO_USER_PASSWORD: ${MONGO_USER_PASSWORD:-mongouserpass}
    networks:
      - api-network
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - mongodb-data:/data/db
      - mongodb-log:/var/log/mongodb
      - mongodb-config:/data/configdb

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${DOCKER_USER:-noname}/playwithchatgpt-api:${API_TAG:-latest}
    ports:
      - ":8080"
    environment:
      MONGO_DATABASE: ${MONGO_DATABASE:-PlayWithChatGPT}
      MONGO_PORT: ${MONGO_PORT:-27017}
      MONGO_HOST: ${MONGO_HOST:-mongodb}
      MONGO_USER_NAME: ${MONGO_USER_NAME:-mongouser}
      MONGO_USER_PASSWORD: ${MONGO_USER_PASSWORD:-mongouserpass}
    networks: 
      - api-network
    depends_on:
      - mongodb
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ${DOCKER_USER:-noname}/playwithchatgpt-web:${WEB_TAG:-latest}
    ports:
      - "80:80"
    networks: 
      - web-network
      - api-network
    depends_on:
      - api
networks:
  api-network:
  web-network:
volumes:
  mongodb-data:
    driver: local
  mongodb-log:
    driver: local
  mongodb-config:
    driver: local
