version: '3'
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${DOCKER_USER:-noname}/playwithchatgpt-api:${API_TAG:-latest}
    ports:
      - ":8080"
    networks: 
      - api-network
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ${DOCKER_USER:-noname}/playwithchatgpt-web:${WEB_TAG:-latest}
    ports:
      - "80:80"
    networks: 
      - web-network
      - api-network
    depends_on:
      - api
networks:
  api-network:
  web-network:
